/**
 * Playcademy Environment Types
 *
 * Auto-generated by Playcademy CLI.
 * Regenerated on: playcademy dev, playcademy init, playcademy db init, playcademy auth init
 *
 * Do not edit - changes will be overwritten.
 */

/// <reference types="./.playcademy/node_modules/@cloudflare/workers-types" />

import type { Context as HonoContext } from './.playcademy/node_modules/hono'
import type { UserInfo } from './node_modules/@playcademy/sdk/dist/types.d.ts'

declare global {
    interface PlaycademyEnv {
        PLAYCADEMY_API_KEY: string
        GAME_ID: string
        PLAYCADEMY_BASE_URL: string
        secrets: Record<string, string>
    }

    interface PlaycademyVariables {
        playcademyUser?: UserInfo
    }

    type Context = HonoContext<{ Bindings: PlaycademyEnv; Variables: PlaycademyVariables }>
}

export {}
